name: warszawabot

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '15 8 * * *'

jobs:
  warszawabot-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY_WARSZAWABOT }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET_WARSZAWABOT }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_WARSZAWABOT }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_WARSZAWABOT }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-1-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-2-
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install distill package
        run: Rscript -e 'install.packages("distill", dependencies = TRUE)'
      - name: Install rmarkdown package
        run: Rscript -e 'install.packages("rmarkdown", dependencies = TRUE)'
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install lubridate package
        run: Rscript -e 'install.packages("lubridate", dependencies = TRUE)'
      - name: Install leaflet package
        run: Rscript -e 'install.packages("leaflet", dependencies = TRUE)'
      - name: Install mapview package
        run: Rscript -e 'install.packages("mapview", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript warszawabot-tweet.R
      - name: Commit plików
        run: |
          git add -A
          git commit -m 'Zapisanie nowych twitow warszawabot'
          git push origin || echo "Zapisuje nowe twity"